on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check-code:
    uses: ./.github/workflows/cargo-check.yml

  build-code:
    if: github.ref != 'refs/heads/dev'
    uses: ./.github/workflows/cargo-build.yml

  test-code:
    uses: ./.github/workflows/cargo-test.yml
